# Missing Data Imputation

Simon Chen

Objective:
      
At the end of this ICE, you will be able to:
- simulate MCAR data or MAR data
- implement common missing data imputation methods
- (optional) compare the performance of missing data imputation methods on an analysis you have done before.

Missing data is very common in any work related to data analysis. Oftentimes, analyses will suffer from the problem that some observations/entries in the dataset are complete. In this ICE, we will explore a few common data imputation methods that deals with missing data.

## Missing data mechanism

First, let's revisit the three general mechanisms of missing data:

- MCAR: Missing complete at random - Whether or not Yi is missing is independent of both Yi and any observed covariate Xi.
- MAR: Missing at Random - Whether or not Yi is missing is independent of Yi given observed covariates Xi.
- NMAR (or sometimes MNAR): Not missing at random/Missing not at random - This is the most generic mechanism, where the cause of the missingness cannot be controlled. Whether or not Yi is missing is not independent even after controlling the observed covariates Xi. You can check out this blog for some more information, examples, and terminologies in missing data.

In practice, you missing data may be MCAR, MAR, or NMAR. Ultimately, it is a decision/judgement/assumption you have to make because we would not be able to observe the compelte dataset. Therefore, in terms of an ICE practice, we are going to mannually generate some missingness in the data to demonstrate MCAR, MAR, and NMAR.

To illustrate, we are going to use the iris dataset, perhaps one of the best known dataset in data science. You can check out some more details about this dataset on UCI repo: https://archive.ics.uci.edu/ml/datasets/iris

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [2]:
# IRIS is included in sci-kit learn. We can directly load it.
# See documentation here: https://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html
irisRaw = datasets.load_iris()

# Convert it to a pandas dataframe for better visualization
iris = pd.DataFrame(data=irisRaw.data, columns=irisRaw.feature_names)
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

## MCAR
MCAR would be the easiest. We can simply sample random proportion of the data and replace them NaN. You can choose to randomly insert missingness into one or multiple columns.

In [3]:
iris_MCAR = iris.copy()

In [4]:
# Set the missingness rate at 30%
missing = 0.3

# Only introduce missing rate to the `sepal length (cm)`.
iris_MCAR.loc[iris_MCAR.sample(frac=missing).index, 'sepal length (cm)'] = np.nan

iris_MCAR

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  NaN               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                NaN               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [5]:
# Alternatively, iterate through all columns and introduce 20% missing to all variables.
for col in iris_MCAR.columns:
    iris_MCAR.loc[iris_MCAR.sample(frac=missing).index, col] = np.nan

## MAR
One easy way to generate an MAR data is to use the weights parameter in pd.sample(). The default ‘None’ results in equal probability weighting. If passed a Series, sample() will align with target object on index. Using a DataFrame column as weights, rows with larger value in the the specified column are more likely to be sampled. Read here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html

In [6]:
iris_MAR = iris.copy()

In [7]:
# Set the missingness rate at 30%
missing = 0.3

# Only introduce missing rate to the `sepal length (cm)`.
iris_MAR.loc[iris_MAR.sample(frac=missing, weights = 'sepal width (cm)').index, 'sepal length (cm)'] = np.nan

iris_MAR

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                NaN               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                NaN               3.0                5.2               2.0
148                NaN               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

## Deletion Methods¶

The most straightforward way to handle missing data is to ignore them. There are two different types of deletion methods:

- Listwise deletion (or sometimes known as casewise deletion)
- Pairwise deletion

## Listwise deletion

It produces unbiased estimation only when the data is MCAR. However, the reduced sample size leads to reduced power. In python, we can use dropna() to perform a listwise deletion. You can see here, as we introduced 30% of missing into the dataset, the sample size is now 105.

In [8]:
iris_MCAR_listwise = iris_MCAR.copy()
iris_MCAR_listwise.dropna()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                  4.9               3.0                1.4               0.2
8                  4.4               2.9                1.4               0.2
14                 5.8               4.0                1.2               0.2
25                 5.0               3.0                1.6               0.2
31                 5.4               3.4                1.5               0.4
35                 5.0               3.2                1.2               0.2
36                 5.5               3.5                1.3               0.2
50                 7.0               3.2                4.7               1.4
59                 5.2               2.7                3.9               1.4
60                 5.0               2.0                3.5               1.0
65                 6.7               3.1                4.4               1.4
69                 5.6               2.5                3.9               1.1
71                 6.1               2.8                4.0               1.3
72                 6.3               2.5                4.9               1.5
76                 6.8               2.8                4.8               1.4
79                 5.7               2.6                3.5               1.0
84                 5.4               3.0                4.5               1.5
94                 5.6               2.7                4.2               1.3
95                 5.7               3.0                4.2               1.2
104                6.5               3.0                5.8               2.2
106                4.9               2.5                4.5               1.7
109                7.2               3.6                6.1               2.5
117                7.7               3.8                6.7               2.2
121                5.6               2.8                4.9               2.0
123                6.3               2.7                4.9               1.8
135                7.7               3.0                6.1               2.3
140                6.7               3.1                5.6               2.4
145                6.7               3.0                5.2               2.3

## Pairwise deletion

Alternatively, we can do pairwise deletion. It only skips the null observation when the it is needed. Therefore, it avoid the data loss issue in listwise deletion to a certain degree. All methods in pandas such as mean, median, sum, etc. uses pairwise deletion by default. You can see that pairwise deletion performs a bit better on MCAR than MAR data (closer to the true estimation).

In [9]:
iris_MCAR_pairwise = iris_MCAR.copy()
iris_MAR_pairwise = iris_MAR.copy()

print("Mean estimation in MCAR data with pairwise deletion",
      iris_MCAR_pairwise['sepal length (cm)'].mean(), 
     "\nSD estimation in MCAR data with pairwise deletion",
      iris_MCAR_pairwise['sepal length (cm)'].std()
     )
print("Mean estimation in MAR data with pairwise deletion",
      iris_MAR_pairwise['sepal length (cm)'].mean(), 
     "\nSD estimation in MAR data with pairwise deletion",
      iris_MAR_pairwise['sepal length (cm)'].std()
     )
print("Mean estimation in the original data",
      iris['sepal length (cm)'].mean(),
      "\nSD estimation in the original data",
      iris['sepal length (cm)'].std()
     )


Mean estimation in MCAR data with pairwise deletion 5.802666666666665 
SD estimation in MCAR data with pairwise deletion 0.7846454412462158
Mean estimation in MAR data with pairwise deletion 5.799999999999999 
SD estimation in MAR data with pairwise deletion 0.8155932244031381
Mean estimation in the original data 5.843333333333335 
SD estimation in the original data 0.8280661279778629


## Single Imputation¶

As opposed to deletion, we can impute (or in plain English -- "guess") the missing value with various imputation methods.

## Simple imputation

The simplest ones include mean/median/model imputation. Read here about the simple imputation in sci-kit learn: https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html#sklearn.impute.SimpleImputer

For MCAR data, simple imputation produces unbiased estimation of marginal means, but underestimates variances, and overestimate correlations.

In [10]:
from sklearn.impute import SimpleImputer
iris_MAR_mean = iris_MAR.copy()

In [11]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(iris_MAR)
print(imp.transform(iris_MAR))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.8 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.8 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [5.8 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [5.8 3.4 1.9 0.2]
 [5.8 3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.8 3.2 1.6 0.2]
 [5.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.8 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [5.8 2.3 1.3 0.3]
 [5.8 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.8 3.8 1.9 0.4]
 [5.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.8 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## Regression Imputation/Conditional Mean Imputation

A more common way to impute the missing value based on regression/anova models. In this case, you are modeling the dependency through the observed covariate(s). This can work fairly well if you can identify the correct covariate(s) that are related to the missingness.

You can basically view the missing values as Ytest and the observed values as Ytrain. And use the observed completed cases to train a prediction model and then predict the missing values with the incompelte cases.

In [12]:
from sklearn import linear_model
iris_MAR_regression = iris_MAR.copy()

In [13]:
iris_MAR_regression_model = iris_MAR_regression.copy().dropna()

model = linear_model.LinearRegression()
Xs = iris_MAR_regression_model['sepal width (cm)'].values.reshape(-1, 1)
ys = iris_MAR_regression_model['sepal length (cm)'].values.reshape(-1, 1)
model.fit(X = Xs, y = ys)

null_index = iris_MAR_regression['sepal length (cm)'].isnull()

na_result = model.predict(iris_MAR_regression[null_index]['sepal width (cm)'].values.reshape(-1, 1))


iris_MAR_regression.loc[iris_MAR_regression['sepal length (cm)'].isnull(), 'sepal length (cm)'] = na_result.reshape(len(na_result),)

iris_MAR_regression

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             5.100000               3.5                1.4               0.2
1             4.900000               3.0                1.4               0.2
2             4.700000               3.2                1.3               0.2
3             4.600000               3.1                1.5               0.2
4             5.000000               3.6                1.4               0.2
..                 ...               ...                ...               ...
145           5.809916               3.0                5.2               2.3
146           6.300000               2.5                5.0               1.9
147           5.809916               3.0                5.2               2.0
148           5.649727               3.4                5.4               2.3
149           5.900000               3.0                5.1               1.8

[150 rows x 4 columns]

## Nearest neighbours or hot-deck imputation

Similarly, you can use other prediction methods to perform the imputation. One a commonly used method is KNN, as a type of hot-deck imputation. Here is the sci-kit learn implementation. By default, it draws from all the variables.

In [14]:
from sklearn.impute import KNNImputer
iris_MAR_knn = iris_MAR.copy()

In [15]:
knn_imputer = KNNImputer(n_neighbors=2, weights="uniform")

knn_imputer.fit_transform(iris_MAR_knn)

array([[5.1 , 3.5 , 1.4 , 0.2 ],
       [4.9 , 3.  , 1.4 , 0.2 ],
       [4.7 , 3.2 , 1.3 , 0.2 ],
       [4.6 , 3.1 , 1.5 , 0.2 ],
       [5.  , 3.6 , 1.4 , 0.2 ],
       [5.4 , 3.9 , 1.7 , 0.4 ],
       [4.6 , 3.4 , 1.4 , 0.3 ],
       [5.  , 3.4 , 1.5 , 0.2 ],
       [4.4 , 2.9 , 1.4 , 0.2 ],
       [4.9 , 3.1 , 1.5 , 0.1 ],
       [5.4 , 3.7 , 1.5 , 0.2 ],
       [4.8 , 3.4 , 1.6 , 0.2 ],
       [4.8 , 3.  , 1.4 , 0.1 ],
       [4.3 , 3.  , 1.1 , 0.1 ],
       [5.45, 4.  , 1.2 , 0.2 ],
       [5.35, 4.4 , 1.5 , 0.4 ],
       [5.4 , 3.9 , 1.3 , 0.4 ],
       [5.1 , 3.5 , 1.4 , 0.3 ],
       [5.7 , 3.8 , 1.7 , 0.3 ],
       [5.1 , 3.8 , 1.5 , 0.3 ],
       [4.95, 3.4 , 1.7 , 0.2 ],
       [5.1 , 3.7 , 1.5 , 0.4 ],
       [5.25, 3.6 , 1.  , 0.2 ],
       [5.1 , 3.3 , 1.7 , 0.5 ],
       [4.9 , 3.4 , 1.9 , 0.2 ],
       [4.75, 3.  , 1.6 , 0.2 ],
       [5.  , 3.4 , 1.6 , 0.4 ],
       [5.2 , 3.5 , 1.5 , 0.2 ],
       [5.2 , 3.4 , 1.4 , 0.2 ],
       [4.75, 3.2 , 1.6 , 0.2 ],
       [4.